tap "buo/cask-upgrade"
tap "cjbassi/ytop"
tap "fabianishere/personal"
tap "guoxbin/guoxbin"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
brew "bandwhich"
brew "bat"
brew "cjbassi/ytop/ytop"
brew "direnv"
brew "dog"
brew "dust"
brew "fabianishere/personal/pam_reattach"
brew "fd"
brew "fish"
brew "fzf"
brew "gettext"
brew "gh"
brew "git"
brew "git-delta"
brew "git-quick-stats"
brew "gnu-tar"
brew "hexyl"
brew "hyperfine"
brew "iperf3"
brew "jq"
brew "lsd"
brew "mas"
brew "mtr"
brew "mysql@5.7", restart_service: true
brew "netcat6"
brew "p7zip"
brew "ripgrep"
brew "rsync"
brew "rustup-init"
brew "sd"
brew "syncthing", restart_service: true
brew "tealdeer"
brew "telnet"
brew "tokei"
brew "tree"
brew "unar"
brew "volta"
brew "zenith"
brew "zoxide"
cask "1password"
cask "adobe-creative-cloud"
cask "alfred"
cask "anylist"
cask "appcleaner"
cask "aurora-hdr"
cask "backblaze"
cask "blue-jeans"
cask "cakebrew"
cask "cleanshot"
cask "daisydisk"
cask "dash"
cask "discord"
cask "downie"
cask "electorrent"
cask "elgato-control-center"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "garmin-express"
cask "github"
cask "google-chrome"
cask "iterm2"
cask "mactracker"
cask "mediainfo"
cask "meta"
cask "monodraw"
cask "movist-pro"
cask "omnigraffle"
cask "paw"
cask "proxyman"
cask "pynsource"
cask "querious"
cask "quicken"
cask "raindropio"
cask "roon"
cask "screens"
cask "soulseek"
cask "soulver"
cask "superduper"
cask "suspicious-package"
cask "the-unarchiver"
cask "tower"
cask "visual-studio-code"
cask "wireshark"
cask "zoom"
mas "Adobe Lightroom", id: 1451544217
mas "AutoMounter", id: 1160435653
mas "Brother P-touch Editor", id: 1453365242
mas "Copied", id: 1026349850
mas "Dato", id: 1470584107
mas "Deliveries", id: 924726344
mas "Discovery", id: 1381004916
mas "Honey", id: 1472777122
mas "iMovie", id: 408981434
mas "JSONPeep", id: 1458969831
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Marked 2", id: 890031187
mas "Microsoft Remote Desktop", id: 1295203466
mas "MindNode", id: 1289197285
mas "Netmo", id: 1192219511
mas "Numbers", id: 409203825
mas "Open In Webmail", id: 1451552749
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Patterns", id: 429449079
mas "PDF Expert", id: 1055273043
mas "Raindrop.io for Safari", id: 957810159
mas "Reeder", id: 1529448980
mas "Slack", id: 803453959
mas "StopTheMadness", id: 1376402589
mas "Taskheat", id: 1431995750
mas "Tweetbot", id: 1384080005
mas "WhatsApp", id: 1147396723
mas "Wipr", id: 1320666476
mas "WireGuard", id: 1451685025
mas "Yoink", id: 457622435
