[default]
extend-ignore-re = [
  # git commit hashes in CHANGELOG.md
  "\\[[0-9a-f]{7}\\]",
  # Line ignore with trailing # spellchecker:disable-line
  "(?Rm)^.*(#|--|//)\\s*spellchecker:disable-line$",
  # Line block with # spellchecker:<on|off>
  "(?s)(#|--|//|)\\s*spellchecker:off.*?\\n\\s*(#|--|//)\\s*spellchecker:on",
  # TLS strings
  "\\bTLS_[A-Z0-9_]+(_anon_[A-Z0-9_]+)?\\b",
]

extend-ignore-words-re = [
  # In my experience, false positive detection in typos occurred for short words.
  #
  # * My typos are increased as the words get longer
  # * Too short often conflict with hash strings especially `ba`: https://github.com/crate-ci/typos/issues/415
  # * Added 2 or 3 character abbreviations as wrong: https://github.com/crate-ci/typos/issues/955
  #
  # So I guess skipping all these detections makes reasonable behaviors for now and for the future.
  "\\A[a-zA-Z]{1,3}\\z",
]

[files]
extend-exclude = [
  "*.css",
  "*.lock",
  "*.min.css",
  "*.min.js",
  "*.plist",
  "*lock.json",
  ".git/",
  ".github/",
  ".typos.toml",
  "_typos.toml",
  "go.mod",
  "go.sum",
  "node_modules",
  "pnpm-lock.yaml",
  "typos.toml",
  "vendor/**/*",
]

  [default.extend-words]
  AKS = "AKS"
  aks = "aks"
  electricrain = "electricrain"
  iterm = "iterm"
  protols = "protols"

[type.fish.extend-words]
doas = "doas"

[type.lua.extend-words]
enew = "enew"
noice = "noice"
vhyrro = "vhyrro"
"}," = "},"

[type.rust.extend-words]
juxt = "juxt"
ratatui = "ratatui"
