[default]
extend-ignore-identifiers-re = [  ]

[files]
extend-exclude = [  ]

[default.extend-words]
# Ignore false-positives
AKS = "AKS"
aks = "aks"
doas = "doas"
electricrain = "electricrain"
enew = "enew"
nd = "nd"
noice = "noice"
ratatui = "ratatui"
