# Bootstrap and build Caddy.
# We need linode on electricrain.
# Downgrade to a 2.7.5 compatible version.

EXTRA := if env_var("HOSTNAME") == "zap" { "--with github.com/caddy-dns/linode@b63fbb996d" } else { "" }

default: xcaddy build install clean

xcaddy:
    @echo "Installing xcaddy..."
    @go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

build:
    @xcaddy build master --with github.com/abiosoft/caddy-json-schema --with github.com/caddy-dns/cloudflare {{ EXTRA }}

install:
    @sudo mv caddy /usr/bin/caddy
    @systemctl restart caddy
    @caddy json-schema --output schema.json

clean:
    @sudo /usr/bin/rm -rf ~/.local/go
