# Bootstrap and build Caddy.
# We need linode on electricrain.

EXTRA := if env_var("HOSTNAME") == "zap" { "--with github.com/ocomsoft/caddy2_linode" } else { "" }

default: xcaddy build install

xcaddy:
    @echo "Installing xcaddy..."
    @go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

build:
    @xcaddy build master --with github.com/abiosoft/caddy-json-schema --with github.com/caddy-dns/cloudflare {{ EXTRA }}

install:
    @sudo mv caddy /usr/bin/caddy
    @systemctl restart caddy
    @caddy json-schema --output schema.json
