# Bootstrap and build Caddy.

# We need linode on electricrain.
EXTRA := if env_var("HOSTNAME") == "zap" { "--with github.com/ocomsoft/caddy2_linode" } else { "" }

default: xcaddy build

xcaddy:
    @echo "Installing xcaddy..."
    @go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

build:
    @xcaddy build --with github.com/caddy-dns/cloudflare {{EXTRA}}
