line-length = 160
[lint]
extend-select = [
  "A",
  "B",
  "E",
  "F",
  "W",
  "C4",
  "FA",
  "PT",
  "UP",
  "ARG",
  "DTZ",
  "EXE",
  "FLY",
  "ICN",
  "INP",
  "ISC",
  "PIE",
  "PYI",
  "RET",
  "RSE",
  "RUF",
  "SIM",
  "SLF",
  "TRY",
  "YTT",
  "G003",
  "G201",
  "G202",
  "ASYNC",
]
ignore = [ "B904", "E501", "ISC001", "RET501", "TRY003" ]
