#!/usr/bin/env fish

# Bootstrap and build Caddy.

if not type -q xcaddy
    echo "Installing xcaddy..."
    command go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
end

switch $HOSTNAME
    # We need linode on electricrain.
    case zap
        command xcaddy build --with github.com/caddy-dns/cloudflare --with github.com/ocomsoft/caddy2_linode
    case '*'
        command xcaddy build --with github.com/caddy-dns/cloudflare
end
