# Don't ask for confirmations
assume_yes = true
skip_notify = true

# Disable specific steps - same options as the command line flag
only = [
    "deb_get",
    "git_repos",
    "system",
]

# Ignore failures for these steps
ignore_failures = [ "git_repos" ]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Run inside tmux
#run_in_tmux = true

# Arguments to pass SSH when upgrading remote systems
#ssh_arguments = "-o ConnectTimeout=2"

# Path to Topgrade executable on remote machines
#remote_topgrade_path = ".cargo/bin/topgrade"

# Arguments to pass tmux when pulling Repositories
#tmux_arguments = "-S /var/tmux.sock"

# Do not set the terminal title
#set_title = false

# Display the time in step titles
# display_time = true

# Cleanup temporary or old files
cleanup = true

[git]
#max_concurrency = 5
# Additional git repositories to pull
repos = [
    "/bits/apps/automatic/extensions/*",
    "/bits/apps/stable-diffusion-webui/extensions/*",
]

# Don't pull the predefined git repos
pull_predefined = false

# Arguments to pass Git when pulling Repositories
arguments = "--rebase --autostash"
