["DevinR528/cargo-sort"]
name = "DevinR528/cargo-sort"
alias = "cargo-sort"
asset_pattern = ""
file_pattern = "cargo-sort"

["TheWaWaR/simple-http-server"]
name = "TheWaWaR/simple-http-server"
alias = "simple-http-server"
asset_pattern = ""
file_pattern = "simple-http-server"

["Timmmm/autorebase"]
name = "Timmmm/autorebase"
alias = "autorebase"
asset_pattern = ""
file_pattern = "autorebase"

["cargo-bins/cargo-binstall"]
name = "cargo-bins/cargo-binstall"
alias = "cargo-binstall"
asset_pattern = 'cargo-binstall-{arch}.*{os}\.zip$'
file_pattern = "cargo-binstall"

["dsully/macos-defaults"]
name = "dsully/macos-defaults"
alias = "macos-defaults"
asset_pattern = ""
file_pattern = "macos-defaults"

["dsully/zoned"]
name = "dsully/zoned"
alias = "zoned"
asset_pattern = ""
file_pattern = "zoned"

["gitext-rs/git-dive"]
name = "gitext-rs/git-dive"
alias = "git-dive"
asset_pattern = ""
file_pattern = "git-dive"

["gitext-rs/git-stack"]
name = "gitext-rs/git-stack"
alias = "git-stack"
asset_pattern = ""
file_pattern = "git-stack"

["glotlabs/gdrive"]
name = "glotlabs/gdrive"
alias = "gdrive"
asset_pattern = ""
file_pattern = "gdrive"

["jreisinger/checkip"]
name = "jreisinger/checkip"
alias = "checkip"
asset_pattern = ""
file_pattern = "checkip"

["kbknapp/cargo-outdated"]
name = "kbknapp/cargo-outdated"
alias = "cargo-outdated"
asset_pattern = ""
file_pattern = "cargo-outdated"

["natesales/q"]
name = "natesales/q"
alias = "q"
asset_pattern = ""
file_pattern = "q"

["nguyenvukhang/gitnu"]
name = "nguyenvukhang/gitnu"
alias = "gitnu"
asset_pattern = ""
file_pattern = "git-nu"

["robiot/rustcat"]
name = "robiot/rustcat"
alias = "rustcat"
asset_pattern = ""
file_pattern = "rcat"

["so-fancy/diff-so-fancy"]
name = "so-fancy/diff-so-fancy"
alias = "diff-so-fancy"
asset_pattern = ""
file_pattern = "diff-so-fancy"

["tuna-f1sh/cyme"]
name = "tuna-f1sh/cyme"
alias = "cyme"
asset_pattern = ""
file_pattern = "cyme"
