["gitext-rs/git-dive"]
alias = "git-dive"
asset_pattern = ""
file_pattern = "git-dive"
name = "gitext-rs/git-dive"

["gitext-rs/git-stack"]
alias = "git-stack"
asset_pattern = ""
file_pattern = "git-stack"
name = "gitext-rs/git-stack"

["jreisinger/checkip"]
alias = "checkip"
asset_pattern = ""
file_pattern = "checkip"
name = "jreisinger/checkip"

["tuna-f1sh/cyme"]
alias = "cyme"
asset_pattern = ""
file_pattern = "cyme"
name = "tuna-f1sh/cyme"
