["cargo-bins/cargo-binstall"]
alias = "cargo-binstall"
asset_pattern = 'cargo-binstall-{arch}.*{os}\.(zip|tgz)$'
file_pattern = "cargo-binstall"
name = "cargo-bins/cargo-binstall"

["gitext-rs/git-dive"]
alias = "git-dive"
asset_pattern = ""
file_pattern = "git-dive"
name = "gitext-rs/git-dive"

["gitext-rs/git-stack"]
alias = "git-stack"
asset_pattern = ""
file_pattern = "git-stack"
name = "gitext-rs/git-stack"

["glotlabs/gdrive"]
alias = "gdrive"
asset_pattern = ""
file_pattern = "gdrive"
name = "glotlabs/gdrive"

["jreisinger/checkip"]
alias = "checkip"
asset_pattern = ""
file_pattern = "checkip"
name = "jreisinger/checkip"

["nguyenvukhang/gitnu"]
alias = "gitnu"
asset_pattern = ""
file_pattern = "git-nu"
name = "nguyenvukhang/gitnu"

["robiot/rustcat"]
alias = "rustcat"
asset_pattern = "rcat-.*?-{os}-{arch}$"
file_pattern = "rcat"
name = "robiot/rustcat"

["so-fancy/diff-so-fancy"]
alias = "diff-so-fancy"
asset_pattern = ""
file_pattern = "diff-so-fancy"
name = "so-fancy/diff-so-fancy"

["taiki-e/cargo-llvm-cov"]
alias = "cargo-llvm-cov"
asset_pattern = ""
file_pattern = "cargo-llvm-cov"
name = "taiki-e/cargo-llvm-cov"

["tuna-f1sh/cyme"]
alias = "cyme"
asset_pattern = ""
file_pattern = "cyme"
name = "tuna-f1sh/cyme"
