tap "buo/cask-upgrade"
tap "cjbassi/ytop"
tap "eth-p/software"
tap "guoxbin/guoxbin"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
brew "act"
brew "azure-cli"
brew "bandwhich"
brew "bat"
brew "cjbassi/ytop/ytop"
brew "clang-format"
brew "code-minimap"
brew "dasel"
brew "direnv"
brew "dog"
brew "dua-cli"
brew "dust"
brew "eth-p/software/bat-extras-batdiff"
brew "eth-p/software/bat-extras-batgrep"
brew "eth-p/software/bat-extras-batman"
brew "eth-p/software/bat-extras-batpipe"
brew "eth-p/software/bat-extras-batwatch"
brew "exiv2"
brew "fclones"
brew "fd"
brew "fish"
brew "fselect"
brew "fzf"
brew "gettext"
brew "gh"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "git-lfs"
brew "git-quick-stats"
brew "gitbatch"
brew "gitui"
brew "gitup"
brew "glow"
brew "gnu-tar"
brew "go"
brew "hexyl"
brew "hyperfine"
brew "iperf3"
brew "jless"
brew "jq"
brew "kubernetes-cli"
brew "less"
brew "lsd"
brew "luarocks"
brew "macchina"
brew "mas"
brew "mtr"
brew "mysql@5.7"
brew "neovim"
brew "onefetch"
brew "openssl@1.1"
brew "openssl@3"
brew "p7zip"
brew "pcre2"
brew "pipx"
brew "python@3.10", link: true
brew "ripgrep"
brew "rsync"
brew "rustup-init"
brew "sd"
brew "selene"
brew "shellcheck"
brew "shellharden"
brew "shfmt"
brew "stylua"
brew "subversion"
brew "syncthing", restart_service: true
brew "tealdeer"
brew "telnet"
brew "terraform"
brew "tokei"
brew "topgrade"
brew "tree"
brew "tree-sitter"
brew "unar"
brew "uncrustify"
brew "vivid"
brew "volta"
brew "websocat"
brew "wget"
brew "xh"
brew "xsv"
brew "xz"
brew "zenith"
brew "zoxide"
cask "1password"
cask "adguard"
cask "alfred"
cask "anylist"
cask "aurora-hdr"
cask "backblaze"
cask "bartender"
cask "cleanshot"
cask "daisydisk"
cask "dash"
cask "devtoys"
cask "discord"
cask "docker"
cask "downie"
cask "electorrent"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "iina"
cask "jetbrains-toolbox"
cask "kaleidoscope"
cask "kitty"
cask "mediainfo"
cask "microsoft-auto-update"
cask "microsoft-outlook"
cask "microsoft-teams"
cask "mimestream"
cask "monodraw"
cask "omnigraffle"
cask "paw"
cask "proxyman"
cask "querious"
cask "quicken"
cask "raindropio"
cask "retrobatch"
cask "rocket"
cask "screens"
cask "signal"
cask "soulver"
cask "stay"
cask "superduper"
cask "suspicious-package"
cask "the-unarchiver"
cask "tower"
cask "transmit"
cask "visual-studio-code"
cask "zoom"
tap "homebrew/core"
tap "homebrew/services"
mas "1Password for Safari", id: 1569813296
mas "Affinity Photo", id: 824183456
mas "Agenda", id: 1287445660
mas "Apple Configurator", id: 1037126344
mas "AutoMounter", id: 1160435653
mas "Book Track", id: 1496543317
mas "Brother P-touch Editor", id: 1453365242
mas "CollageIt 3 Lite", id: 675540049
mas "Darkroom", id: 953286746
mas "Dato", id: 1470584107
mas "Deliveries", id: 924726344
mas "DevCleaner", id: 1388020431
mas "Discovery", id: 1381004916
mas "Disk Speed Test", id: 425264550
mas "Handy Converter", id: 1193672923
mas "JSONPeep", id: 1458969831
mas "Jiffy", id: 1502527999
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Marked 2", id: 890031187
mas "Matter", id: 1548677272
mas "MetaImage", id: 1397099749
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft To Do", id: 1274495053
mas "MindNode", id: 1289197285
mas "Netmo", id: 1192219511
mas "Numbers", id: 409203825
mas "PDF Expert", id: 1055273043
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Patterns", id: 429449079
mas "Play", id: 1596506190
mas "RAW Power", id: 1157116444
mas "Reeder", id: 1529448980
mas "Save to Raindrop.io", id: 1549370672
mas "Slack", id: 803453959
mas "SmugMug", id: 1115348888
mas "Spark", id: 1176895641
mas "StopTheMadness", id: 1376402589
mas "Str*Viewer", id: 1501259216
mas "TrashMe 3", id: 1490879410
mas "Tripsy", id: 1429967544
mas "Tweaks for Twitter", id: 1567751529
mas "Tweetbot", id: 1384080005
mas "Userscripts", id: 1463298887
mas "WireGuard", id: 1451685025
mas "Yoink", id: 457622435
mas "iMovie", id: 408981434
mas "iPreview", id: 1519213509
mas "m-wiki", id: 1480168619
