#:schema https://raw.githubusercontent.com/akiomik/mado/refs/heads/main/pkg/json-schema/mado.json

[lint]
respect-ignore = true
respect-gitignore = true
output-format = "concise"
quiet = false
exclude = []
rules = [
  "MD001",
  "MD002",
  "MD003",
  "MD004",
  "MD005",
  "MD006",
  "MD007",
  "MD009",
  "MD010",
  "MD012",
  "MD013",
  "MD014",
  "MD018",
  "MD019",
  "MD020",
  "MD021",
  "MD022",
  "MD023",
  "MD024",
  "MD025",
  "MD026",
  "MD027",
  "MD028",
  "MD029",
  "MD030",
  "MD031",
  "MD032",
  "MD033",
  # "MD034", # no-bare-urls
  "MD035",
  "MD036",
  "MD037",
  "MD038",
  "MD039",
  "MD040",
  "MD041",
  "MD046",
  "MD047",
]

[lint.md002]
level = 1

[lint.md003]
style = "consistent"

[lint.md004]
style = "consistent"

[lint.md007]
indent = 4

[lint.md013]
line-length = 160
code-blocks = true
tables = true

[lint.md024]
allow-different-nesting = true

[lint.md025]
level = 1

[lint.md026]
punctuation = ".,;:!?"

[lint.md029]
style = "ordered"

[lint.md030]
ul-single = 1
ol-single = 1
ul-multi = 1
ol-multi = 1

[lint.md033]
allowed-elements = []

[lint.md035]
style = "consistent"

[lint.md036]
punctuation = ".,;:!?"

[lint.md041]
level = 1

[lint.md046]
style = "fenced"
