# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

palette = "onenord"

format = '''
($username)(@$hostname:)\[$directory\] \(($git_branch)( $git_status)\)
\$ '''

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
error_symbol = '\$'
success_symbol = '\$'

[c]
disabled = true

[cmake]
disabled = true

[deno]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
format = '[$path]($style)'
style = "cyan"

[git_branch]
format = "[$branch]($style)"
style = "bold white"
symbol = ""

[git_status]
disabled = false
format = "[$staged$modified]($style)"
modified = "*"
staged = "+"
style = "white"

[golang]
disabled = true

[gradle]
disabled = true

[helm]
disabled = true

[hostname]
format = '[$hostname]($style)'
ssh_only = true
style = "cyan"

[java]
disabled = true

[jobs]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

# [line_break]
# disabled = false

[lua]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[status]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[username]
format = '[$user]($style)'
style_root = 'bold red'
style_user = 'cyan'

[zig]
disabled = true

[palettes.onenord]
bg = "#2E3440"
blue = "#81A1C1"
cyan = "#88C0D0"
dark_blue = "#5E81AC"
dark_pink = "#E44675"
dark_red = "#BF616A"
fg = "#C8D0E0"
fg_light = "#E5E9F0"
gray = "#646A76"
green = "#A3BE8C"
light_gray = "#6C7A96"
light_green = "#8FBCBB"
light_purple = "#B48EAD"
light_red = "#DE878F"
none = "NONE"
orange = "#D08F70"
pink = "#E85B7A"
purple = "#B988B0"
red = "#D57780"
yellow = "#EBCB8B"
