[formatting]
# Append trailing commas for multi-line arrays.
array_trailing_comma = true

# Expand arrays to multiple lines that exceed the maximum column width.
array_auto_expand = true

# Collapse arrays that don't exceed the maximum column width and don't contain comments.
array_auto_collapse = false

# Omit white space padding from single-line arrays
compact_arrays = false

# Omit white space padding from the start and end of inline tables.
compact_inline_tables = false

# Indent based on tables and arrays of tables and their subtables, subtables out of order are not indented.
indent_tables = true

# Add trailingnewline at the end of the file if not present.
trailing_newline = false

# Alphabetically reorder keys that are not separated by empty lines.
reorder_keys = true
