[core]
markdown.file_extensions = [ "md", "markdown" ]

# Enable GitLab Flavored Markdown heading ID disambiguation method described
# in https://docs.gitlab.com/ee/user/markdown.html#heading-ids-and-links.
# This enables multiple headings with equal IDs to be deterministically
# referenced by links and impacts ID generation in "Table of Contents"
# code action.
markdown.glfm_heading_ids.enable = true

# Use incremental resolution of project-wide references.
# This is much more efficient but is currently experimental
incremental_references = false

[code_action]
toc.enable = false

# Enable/disable "Create missing linked file" code action
create_missing_file.enable = true

[completion]
# The maximum number of candidates returned for a completion
candidates = 20

# The style of wiki links completion.
# Other values include:
# * "file-stem" to complete using file name without an extension,
# * "file-path-stem" same as above but using file path.
wiki.style = "title-slug"
