directory: /bits/music/flac
asciify_paths: no
color: yes
plugins: chroma discogs fetchart ftintitle mbsync scrub replaygain

original_date: yes

replaygain:
    backend: ffmpeg

paths:
    default: %left{%upper{$albumartist},1}/$albumartist/$album/$disc-$track - $artist - $title
    comp: V/Various Artists/$album/$disc-$track - $artist - $title

import:
    move: yes
    incremental: yes
    resume: yes

match:
    preferred:
        countries: ['US', 'GB|UK']
        media: ['CD', 'Digital Media|File']
        original_year: yes
