tap "buo/cask-upgrade"
tap "bvaisvil/zenith"
tap "cjbassi/ytop"
tap "fabianishere/personal"
tap "guoxbin/guoxbin"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
brew "bandwhich"
brew "bat"
brew "boxes"
brew "direnv"
brew "dog"
brew "dust"
brew "fd"
brew "fish"
brew "fzf"
brew "gettext"
brew "gh"
brew "git"
brew "git-delta"
brew "git-quick-stats"
brew "gnu-tar"
brew "hexyl"
brew "hyperfine"
brew "iperf3"
brew "jq"
brew "loc"
brew "lsd"
brew "mas"
brew "mdcat"
brew "mtr"
brew "mysql@5.7", restart_service: true
brew "netcat6"
brew "nmap"
brew "p7zip"
brew "procs"
brew "ripgrep"
brew "rsync"
brew "rustup-init"
brew "sd"
brew "subversion"
brew "syncthing", restart_service: true
brew "telnet"
brew "tokei"
brew "tree"
brew "unar"
brew "volta"
brew "websocat"
brew "xh"
brew "xz"
brew "zenith"
brew "zoxide"
brew "bvaisvil/zenith/zenith"
brew "cjbassi/ytop/ytop"
brew "fabianishere/personal/pam_reattach"
cask "1password"
cask "adobe-creative-cloud"
cask "alfred"
cask "anylist"
cask "appcleaner"
cask "aurora-hdr"
cask "backblaze"
cask "cakebrew"
cask "cisco-proximity"
cask "cleanshot"
cask "daisydisk"
cask "dash"
cask "discord"
cask "downie"
cask "electorrent"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "garmin-express"
cask "github"
cask "hex-fiend"
cask "iterm2"
cask "macdive"
cask "mactracker"
cask "mediainfo"
cask "meta"
cask "microsoft-teams"
cask "mimestream"
cask "monodraw"
cask "movist-pro"
cask "notion"
cask "omnigraffle"
cask "paw"
cask "proxyman"
cask "pynsource"
cask "querious"
cask "quicken"
cask "raindropio"
cask "rocket"
cask "roon"
cask "screens"
cask "signal"
cask "soulseek"
cask "soulver"
cask "stay"
cask "superduper"
cask "suspicious-package"
cask "the-unarchiver"
cask "tower"
cask "transmit"
cask "visual-studio-code"
cask "wireshark"
cask "zoom"
mas "Adobe Lightroom", id: 1451544217
mas "Affinity Designer", id: 824171161
mas "Agenda", id: 1287445660
mas "AutoMounter", id: 1160435653
mas "Brother P-touch Editor", id: 1453365242
mas "Copied", id: 1026349850
mas "Craft", id: 1487937127
mas "Darkroom", id: 953286746
mas "Dato", id: 1470584107
mas "Deliveries", id: 924726344
mas "Discovery", id: 1381004916
mas "hare", id: 1538324606
mas "Honey", id: 1472777122
mas "Hush", id: 1544743900
mas "iMovie", id: 408981434
mas "iPreview", id: 1519213509
mas "JSONPeep", id: 1458969831
mas "Keynote", id: 409183694
mas "m-wiki", id: 1480168619
mas "Magnet", id: 441258766
mas "Marked 2", id: 890031187
mas "MetaImage", id: 1397099749
mas "Microsoft Outlook", id: 985367838
mas "Microsoft Remote Desktop", id: 1295203466
mas "Mindlist", id: 1505964697
mas "MindNode", id: 1289197285
mas "Netmo", id: 1192219511
mas "NextDNS", id: 1464122853
mas "Numbers", id: 409203825
mas "Octotree", id: 1457450145
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Patterns", id: 429449079
mas "PDF Expert", id: 1055273043
mas "PhotoMill", id: 778590574
mas "PhotoSweeper", id: 463362050
mas "Pricy", id: 1538659032
mas "RAW Power", id: 1157116444
mas "Reeder", id: 1529448980
mas "Save to Raindrop.io", id: 1549370672
mas "Scenecuts Helper", id: 1540491573
mas "SessionRestore", id: 1463334954
mas "Slack", id: 803453959
mas "StopTheMadness", id: 1376402589
mas "Str*Viewer", id: 1501259216
mas "Tab Space", id: 1473726602
mas "Taskheat", id: 1431995750
mas "Tweetbot", id: 1384080005
mas "Userscripts", id: 1463298887
mas "WiFi Explorer", id: 494803304
mas "WiFi Signal", id: 525912054
mas "Wipr", id: 1320666476
mas "WireGuard", id: 1451685025
mas "Yoink", id: 457622435
mas "Zappos", id: 392988420
